import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
const browser = await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', headless:true});
const page = await browser.newPage({viewport:{width:1440,height:1100}});
const errors=[];
page.on('pageerror',e=>errors.push(e.message));
page.on('console',m=>{if(m.type()==='error') errors.push(m.text())});
await page.goto(process.env.DEMO_URL || 'http://localhost:5173/');
await page.getByRole('heading',{name:'Your AI receptionist. Always available.'}).waitFor();
const send = async text => {await page.getByRole('textbox',{name:'Ask me anything'}).fill(text);await page.getByRole('button',{name:'Send message',exact:true}).click();await page.getByText('Thinking',{exact:true}).waitFor({state:'hidden'});};
await page.getByRole('button',{name:'Opening hours',exact:true}).click();
await page.getByText(/We’re open Monday–Saturday/).waitFor();
await send('How much is a gel manicure?');
await page.getByText(/Gel Manicure is \$38/).waitFor();
await send('I would like to book a gel manicure');
await page.getByRole('button',{name:'3:00 PM',exact:true}).click();
await page.getByRole('button',{name:'Emily',exact:true}).click();
await page.getByText('APPOINTMENT CONFIRMED',{exact:true}).waitFor();
await page.getByText('KF-2048',{exact:true}).waitFor();
await page.reload();
await page.getByText('KF-2048',{exact:true}).waitFor();
await send('reschedule');
await page.getByRole('button',{name:'5:00 PM',exact:true}).last().click();
await page.getByRole('button',{name:'Sophia',exact:true}).click();
await page.getByText('Your appointment has been rescheduled. You’re all set.').waitFor();
assert.equal(await page.getByText('1 appointment saved',{exact:true}).count(),1);
await page.screenshot({path:'/tmp/khaifrost-desktop.png',fullPage:true});
await page.getByRole('button',{name:'Reset Session',exact:true}).click();
assert.equal(await page.getByText('APPOINTMENT CONFIRMED',{exact:true}).count(),0);
await page.reload();
assert.equal(await page.getByText('KF-2048',{exact:true}).count(),0);
await page.getByRole('button',{name:/Book an appointment/}).click();
await page.getByRole('button',{name:'2:00 PM',exact:true}).waitFor();
await page.getByRole('button',{name:'Reset Session',exact:true}).click();
await page.getByRole('button',{name:'Book appointment',exact:true}).click();
await page.getByRole('button',{name:'Classic Manicure',exact:true}).click();
await page.getByRole('button',{name:'2:00 PM',exact:true}).click();
await page.getByRole('button',{name:'Anna',exact:true}).click();
await page.getByText('APPOINTMENT CONFIRMED',{exact:true}).waitFor();
await page.getByRole('button',{name:'Talk to staff',exact:true}).click();
await page.getByText(/For assistance from a team member/).waitFor();
for(const width of [768,390,320]) {await page.setViewportSize({width,height:900});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth),false,`Overflow at ${width}`);await page.screenshot({path:`/tmp/khaifrost-${width}.png`,fullPage:true});}
await page.getByRole('button',{name:'Reset Session',exact:true}).click();
await page.getByRole('button',{name:'Opening hours',exact:true}).click();
await page.getByRole('button',{name:'Reset Session',exact:true}).click();
await page.waitForTimeout(1100);
assert.equal(await page.getByText(/We’re open Monday–Saturday/).count(),0);
const fallback=await browser.newContext();
await fallback.addInitScript(()=>{window.SpeechRecognition=undefined;window.webkitSpeechRecognition=undefined;});
const fallbackPage=await fallback.newPage();
await fallbackPage.goto(process.env.DEMO_URL || 'http://localhost:5173/');
await fallbackPage.getByRole('button',{name:'Start voice conversation',exact:true}).click();
await fallbackPage.getByText(/Voice input isn’t supported/).waitFor();
await fallbackPage.getByRole('textbox').fill('hello');
assert.equal(await fallbackPage.getByRole('textbox').inputValue(),'hello');
assert.deepEqual(errors,[]);
console.log('PASS: hours, pricing, service/time/staff booking, confirmation, reload persistence, rescheduling, scenarios, handoff, reset during response, voice fallback, desktop/tablet/mobile overflow, zero console/page errors.');
await browser.close();
